site:
  name: "ðŸ”¥ Micro Wiki"
  description: "Mon wiki personnel"
  base_url: "/"
  author: "Paul Walczak"
  repo_url: "https://github.com/Polo-Wolo/micro_wiki"


paths:
  notes: "notes"

navbar:
  brand:
    label: "ðŸ”¥ Micro Wiki"
    url: "/"

  items:
    - label: "Tags"
      url: "/tags"
    - label: "Portfolio"
      url: "/portfolio"
