site:
  name: "ðŸ”¥ Micro Wiki"
  description: "Mon wiki personnel"
  base_url: "/"


paths:
  notes: "notes"

navbar:
  brand:
    label: "ðŸ”¥ Micro Wiki"
    url: "/"

  items:
    - label: "Tags"
      url: "/tags"
    - label: "Portfolio"
      url: "/portfolio"
